[build]
include_ext = ["go", "templ", "html"]
exclude_regex = [".*_templ.go"]
pre_cmd = ["templ generate"]
send_interrupt = true
stop_on_error = true
cmd = "go build -o ./tmp/web dev_web.go"
bin = "tmp/web"

[proxy]
enabled = true
proxy_port = 8081
app_port = 9092
