[build]
include_ext = ["go", "tmpl", "templ", "html"]
exclude_regex = [".*_templ.go"]
pre_cmd = ["templ generate"]
cmd = "GODEBUG=gctrace=1 go build -o ./tmp/main ."
send_interrupt = true
stop_on_error = true

[proxy]
enabled = true
proxy_port = 8080
app_port = 9092

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
