services:
  aftermath-migrate:
    image: aftermath-migrate
    build:
      dockerfile: Dockerfile.migrate
    command: migrate apply --allow-dirty --dir "file:///migrations" --tx-mode all --url "sqlite:///data/${DATABASE_NAME}?_fk=1"
    volumes:
      - ${DATABASE_PATH}:/data
    networks:
      - dokploy-network

  aftermath-service:
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_PATH=/data
    depends_on:
      aftermath-migrate:
        condition: service_completed_successfully
    volumes:
      - ${DATABASE_PATH}:/data

    image: aftermath-service
    build:
      dockerfile: Dockerfile
      args:
        - GO_MEM_LIMIT=122MiB
    restart: always
    deploy:
      resources:
        reservations:
          memory: 128m
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aftermath-monorepo-compose.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.aftermath-monorepo-compose.entrypoints=websecure"
      - "traefik.http.routers.aftermath-monorepo-compose.tls.certResolver=letsencrypt"
      - "traefik.http.services.aftermath-monorepo-compose.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
