services:
  aftermath-migrate:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-migrate-base

  aftermath-service:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-service-base
    environment:
      # use the default port from .env
      - DATABASE_PATH=/data # this is the path inside a container and needs to match the volume mount
    ports:
      - "${PORT}:${PORT}"
