services:
  aftermath-migrate:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-migrate-base
    network_mode: "host"

  aftermath-service:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-service-base
    environment:
      # use the default port from .env
      - DATABASE_PATH=/data # this is the path inside a contianer and needs to match the volume mount
    network_mode: "host"
