services:
  aftermath-migrate:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-migrate-base
    network_mode: "host"

  aftermath-service:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-service-base
    environment:
      - PORT=3000
      - DATABASE_PATH=/data
    network_mode: "host"
