FROM golang:1.23-bookworm as builder-go

RUN go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest  

COPY ./internal/database/migrations /migrations

ENTRYPOINT [ "migrate" ]