services:
  aftermath-database:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-database-base
    restart: always
    ports:
      - "5432:5432"

  aftermath-collector:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-collector-base
    restart: no
    command: --backend=aftermath-service:${PRIVATE_SERVER_PORT}

  aftermath-migrate:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-migrate-base
    restart: no

  aftermath-service:
    extends:
      file: docker-compose.base.yaml
      service: aftermath-service-base
    restart: no
    environment:
      # use the default port from .env
      - DATABASE_PATH=/data # this is the path inside a container and needs to match the volume mount
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      aftermath-migrate:
        condition: service_completed_successfully
