version: "3"

dotenv:
  - ".env"

tasks:
  test:
    desc: runs tests
    cmds:
      - go run {{ .PRISMA_CLIENT }} db push {{ .PRISMA_SCHEMA }}
      - |
        if [ -z "{{ .CLI_ARGS }}" ]; then
          go test -timeout 30s --count=1 -v ./...
        else
          go test -timeout 30s --count=1 -v -run {{ .CLI_ARGS }}
        fi

  ent-generate:
    desc: generate go code for the ent schema directory
    cmd: go generate internal/database/ent

  db-migrate:
    desc: generate migrations
    cmd: atlas migrate hash --dir "file://internal/database/ent/migrate/migrations" && atlas migrate diff {{.CLI_ARGS}} --dir "file://internal/database/ent/migrate/migrations" --to "ent://internal/database/ent/schema" --dev-url "sqlite://file?mode=memory&_fk=1"
  db-migrate-apply:
    desc: apply migrations using atlas
    cmd: atlas migrate apply --allow-dirty --dir "file://internal/database/ent/migrate/migrations" --tx-mode all --url "sqlite://${DATABASE_PATH}?_fk=1"

  dev:
    desc: Start a local dev server
    cmds:
      - air
