version: "3"

dotenv:
  - ".env"

vars:
  PRISMA_CLIENT: github.com/steebchen/prisma-client-go@v0.37.0
  PRISMA_SCHEMA: --schema ./internal/database/prisma/schema.prisma

tasks:
  prisma-install:
    desc: installs the correct version of prisma
    cmd: go get {{ .PRISMA_CLIENT }}

  prisma:
    desc: run a custom prisma command by adding `-- some command` to this task
    cmd: go run {{ .PRISMA_CLIENT }} {{ .PRISMA_SCHEMA }} {{ .CLI_ARGS }}

  db-push:
    desc: sync the database with the schema for development
    cmd: go run {{ .PRISMA_CLIENT }} db push {{ .PRISMA_SCHEMA }} 

  db-generate:
    desc: re-generate the Go client
    cmd: go run {{ .PRISMA_CLIENT }} generate {{ .PRISMA_SCHEMA }} 

  db-migrate-dev:
    desc: for production use, create a migration locally
    cmd: go run {{ .PRISMA_CLIENT }} migrate dev {{ .PRISMA_SCHEMA }} 

  db-migrate-deploy:
    desc: sync production database with migrations
    cmd: go run {{ .PRISMA_CLIENT }} migrate deploy {{ .PRISMA_SCHEMA }} 

  dev:
    desc: Start a local dev server
    deps:
      - db-push
    cmds:
      - air
