version: "3"

dotenv:
  - ".env"

vars:
  ENT_CMD: go run -mod=mod entgo.io/ent/cmd/ent
  ENT_DIRECTORY: internal/database/ent/schema

tasks:
  test:
    desc: runs tests
    cmds:
      - go run {{ .PRISMA_CLIENT }} db push {{ .PRISMA_SCHEMA }}
      - |
        if [ -z "{{ .CLI_ARGS }}" ]; then
          go test -timeout 30s --count=1 -v ./...
        else
          go test -timeout 30s --count=1 -v -run {{ .CLI_ARGS }}
        fi

  ent-new:
    desc: init a new schema with a given name
    cmd: '{{.ENT_CMD}} new --target {{.ENT_DIRECTORY}} {{.CLI_ARGS}}'

  ent-generate:
    desc: generate go code for the ent schema directory
    cmd: go generate internal/database/ent

  db-migrate:
    desc: generate migrations
    cmd: atlas migrate diff init --dir "file://internal/database/ent/migrate/migrations" --to "ent://internal/database/ent/schema" --dev-url "sqlite://tmp/file?mode=memory&_fk=1"
  db-migrate-apply:
    desc: apply migrations using atlas
    cmd: ${ATLAS_TEMP_DIR} migrate apply --allow-dirty --dir "file://internal/database/ent/migrate/migrations" --tx-mode all --url "libsql+ws://0.0.0.0:8080"

  dev:
    desc: Start a local dev server
    cmds:
      - air
