// Code generated by ent, DO NOT EDIT.

package vehiclesnapshot

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
	"github.com/cufee/aftermath/internal/database/models"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// VehicleID applies equality check predicate on the "vehicle_id" field. It's identical to VehicleIDEQ.
func VehicleID(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldVehicleID, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldReferenceID, v))
}

// Battles applies equality check predicate on the "battles" field. It's identical to BattlesEQ.
func Battles(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldBattles, v))
}

// LastBattleTime applies equality check predicate on the "last_battle_time" field. It's identical to LastBattleTimeEQ.
func LastBattleTime(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldLastBattleTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v models.SnapshotType) predicate.VehicleSnapshot {
	vc := v
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v models.SnapshotType) predicate.VehicleSnapshot {
	vc := v
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...models.SnapshotType) predicate.VehicleSnapshot {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VehicleSnapshot(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...models.SnapshotType) predicate.VehicleSnapshot {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldType, v...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContainsFold(FieldAccountID, v))
}

// VehicleIDEQ applies the EQ predicate on the "vehicle_id" field.
func VehicleIDEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldVehicleID, v))
}

// VehicleIDNEQ applies the NEQ predicate on the "vehicle_id" field.
func VehicleIDNEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldVehicleID, v))
}

// VehicleIDIn applies the In predicate on the "vehicle_id" field.
func VehicleIDIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldVehicleID, vs...))
}

// VehicleIDNotIn applies the NotIn predicate on the "vehicle_id" field.
func VehicleIDNotIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldVehicleID, vs...))
}

// VehicleIDGT applies the GT predicate on the "vehicle_id" field.
func VehicleIDGT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldVehicleID, v))
}

// VehicleIDGTE applies the GTE predicate on the "vehicle_id" field.
func VehicleIDGTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldVehicleID, v))
}

// VehicleIDLT applies the LT predicate on the "vehicle_id" field.
func VehicleIDLT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldVehicleID, v))
}

// VehicleIDLTE applies the LTE predicate on the "vehicle_id" field.
func VehicleIDLTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldVehicleID, v))
}

// VehicleIDContains applies the Contains predicate on the "vehicle_id" field.
func VehicleIDContains(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContains(FieldVehicleID, v))
}

// VehicleIDHasPrefix applies the HasPrefix predicate on the "vehicle_id" field.
func VehicleIDHasPrefix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasPrefix(FieldVehicleID, v))
}

// VehicleIDHasSuffix applies the HasSuffix predicate on the "vehicle_id" field.
func VehicleIDHasSuffix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasSuffix(FieldVehicleID, v))
}

// VehicleIDEqualFold applies the EqualFold predicate on the "vehicle_id" field.
func VehicleIDEqualFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEqualFold(FieldVehicleID, v))
}

// VehicleIDContainsFold applies the ContainsFold predicate on the "vehicle_id" field.
func VehicleIDContainsFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContainsFold(FieldVehicleID, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDContains applies the Contains predicate on the "reference_id" field.
func ReferenceIDContains(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContains(FieldReferenceID, v))
}

// ReferenceIDHasPrefix applies the HasPrefix predicate on the "reference_id" field.
func ReferenceIDHasPrefix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasPrefix(FieldReferenceID, v))
}

// ReferenceIDHasSuffix applies the HasSuffix predicate on the "reference_id" field.
func ReferenceIDHasSuffix(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldHasSuffix(FieldReferenceID, v))
}

// ReferenceIDEqualFold applies the EqualFold predicate on the "reference_id" field.
func ReferenceIDEqualFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEqualFold(FieldReferenceID, v))
}

// ReferenceIDContainsFold applies the ContainsFold predicate on the "reference_id" field.
func ReferenceIDContainsFold(v string) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldContainsFold(FieldReferenceID, v))
}

// BattlesEQ applies the EQ predicate on the "battles" field.
func BattlesEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldBattles, v))
}

// BattlesNEQ applies the NEQ predicate on the "battles" field.
func BattlesNEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldBattles, v))
}

// BattlesIn applies the In predicate on the "battles" field.
func BattlesIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldBattles, vs...))
}

// BattlesNotIn applies the NotIn predicate on the "battles" field.
func BattlesNotIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldBattles, vs...))
}

// BattlesGT applies the GT predicate on the "battles" field.
func BattlesGT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldBattles, v))
}

// BattlesGTE applies the GTE predicate on the "battles" field.
func BattlesGTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldBattles, v))
}

// BattlesLT applies the LT predicate on the "battles" field.
func BattlesLT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldBattles, v))
}

// BattlesLTE applies the LTE predicate on the "battles" field.
func BattlesLTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldBattles, v))
}

// LastBattleTimeEQ applies the EQ predicate on the "last_battle_time" field.
func LastBattleTimeEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldEQ(FieldLastBattleTime, v))
}

// LastBattleTimeNEQ applies the NEQ predicate on the "last_battle_time" field.
func LastBattleTimeNEQ(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNEQ(FieldLastBattleTime, v))
}

// LastBattleTimeIn applies the In predicate on the "last_battle_time" field.
func LastBattleTimeIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldIn(FieldLastBattleTime, vs...))
}

// LastBattleTimeNotIn applies the NotIn predicate on the "last_battle_time" field.
func LastBattleTimeNotIn(vs ...int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldNotIn(FieldLastBattleTime, vs...))
}

// LastBattleTimeGT applies the GT predicate on the "last_battle_time" field.
func LastBattleTimeGT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGT(FieldLastBattleTime, v))
}

// LastBattleTimeGTE applies the GTE predicate on the "last_battle_time" field.
func LastBattleTimeGTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldGTE(FieldLastBattleTime, v))
}

// LastBattleTimeLT applies the LT predicate on the "last_battle_time" field.
func LastBattleTimeLT(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLT(FieldLastBattleTime, v))
}

// LastBattleTimeLTE applies the LTE predicate on the "last_battle_time" field.
func LastBattleTimeLTE(v int) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.FieldLTE(FieldLastBattleTime, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VehicleSnapshot) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VehicleSnapshot) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VehicleSnapshot) predicate.VehicleSnapshot {
	return predicate.VehicleSnapshot(sql.NotPredicates(p))
}
