// Code generated by ent, DO NOT EDIT.

package widgetsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldReferenceID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldTitle, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldUserID, v))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldSnapshotID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDContains applies the Contains predicate on the "reference_id" field.
func ReferenceIDContains(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContains(FieldReferenceID, v))
}

// ReferenceIDHasPrefix applies the HasPrefix predicate on the "reference_id" field.
func ReferenceIDHasPrefix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasPrefix(FieldReferenceID, v))
}

// ReferenceIDHasSuffix applies the HasSuffix predicate on the "reference_id" field.
func ReferenceIDHasSuffix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasSuffix(FieldReferenceID, v))
}

// ReferenceIDEqualFold applies the EqualFold predicate on the "reference_id" field.
func ReferenceIDEqualFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEqualFold(FieldReferenceID, v))
}

// ReferenceIDContainsFold applies the ContainsFold predicate on the "reference_id" field.
func ReferenceIDContainsFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContainsFold(FieldReferenceID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContainsFold(FieldTitle, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContainsFold(FieldUserID, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// SnapshotIDGT applies the GT predicate on the "snapshot_id" field.
func SnapshotIDGT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGT(FieldSnapshotID, v))
}

// SnapshotIDGTE applies the GTE predicate on the "snapshot_id" field.
func SnapshotIDGTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldGTE(FieldSnapshotID, v))
}

// SnapshotIDLT applies the LT predicate on the "snapshot_id" field.
func SnapshotIDLT(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLT(FieldSnapshotID, v))
}

// SnapshotIDLTE applies the LTE predicate on the "snapshot_id" field.
func SnapshotIDLTE(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldLTE(FieldSnapshotID, v))
}

// SnapshotIDContains applies the Contains predicate on the "snapshot_id" field.
func SnapshotIDContains(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContains(FieldSnapshotID, v))
}

// SnapshotIDHasPrefix applies the HasPrefix predicate on the "snapshot_id" field.
func SnapshotIDHasPrefix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasPrefix(FieldSnapshotID, v))
}

// SnapshotIDHasSuffix applies the HasSuffix predicate on the "snapshot_id" field.
func SnapshotIDHasSuffix(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldHasSuffix(FieldSnapshotID, v))
}

// SnapshotIDIsNil applies the IsNil predicate on the "snapshot_id" field.
func SnapshotIDIsNil() predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldIsNull(FieldSnapshotID))
}

// SnapshotIDNotNil applies the NotNil predicate on the "snapshot_id" field.
func SnapshotIDNotNil() predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldNotNull(FieldSnapshotID))
}

// SnapshotIDEqualFold applies the EqualFold predicate on the "snapshot_id" field.
func SnapshotIDEqualFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldEqualFold(FieldSnapshotID, v))
}

// SnapshotIDContainsFold applies the ContainsFold predicate on the "snapshot_id" field.
func SnapshotIDContainsFold(v string) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.FieldContainsFold(FieldSnapshotID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.WidgetSettings {
	return predicate.WidgetSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.WidgetSettings {
	return predicate.WidgetSettings(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WidgetSettings) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WidgetSettings) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WidgetSettings) predicate.WidgetSettings {
	return predicate.WidgetSettings(sql.NotPredicates(p))
}
