// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cufee/aftermath/internal/database/ent/db/account"
	"github.com/cufee/aftermath/internal/database/ent/db/achievementssnapshot"
	"github.com/cufee/aftermath/internal/database/models"
	"github.com/cufee/am-wg-proxy-next/v2/types"
)

// AchievementsSnapshot is the model entity for the AchievementsSnapshot schema.
type AchievementsSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// Type holds the value of the "type" field.
	Type models.SnapshotType `json:"type,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// ReferenceID holds the value of the "reference_id" field.
	ReferenceID string `json:"reference_id,omitempty"`
	// Battles holds the value of the "battles" field.
	Battles int `json:"battles,omitempty"`
	// LastBattleTime holds the value of the "last_battle_time" field.
	LastBattleTime int64 `json:"last_battle_time,omitempty"`
	// Data holds the value of the "data" field.
	Data types.AchievementsFrame `json:"data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AchievementsSnapshotQuery when eager-loading is set.
	Edges        AchievementsSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AchievementsSnapshotEdges holds the relations/edges for other nodes in the graph.
type AchievementsSnapshotEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AchievementsSnapshotEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AchievementsSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case achievementssnapshot.FieldData:
			values[i] = new([]byte)
		case achievementssnapshot.FieldCreatedAt, achievementssnapshot.FieldUpdatedAt, achievementssnapshot.FieldBattles, achievementssnapshot.FieldLastBattleTime:
			values[i] = new(sql.NullInt64)
		case achievementssnapshot.FieldID, achievementssnapshot.FieldType, achievementssnapshot.FieldAccountID, achievementssnapshot.FieldReferenceID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AchievementsSnapshot fields.
func (as *AchievementsSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case achievementssnapshot.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				as.ID = value.String
			}
		case achievementssnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				as.CreatedAt = value.Int64
			}
		case achievementssnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				as.UpdatedAt = value.Int64
			}
		case achievementssnapshot.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				as.Type = models.SnapshotType(value.String)
			}
		case achievementssnapshot.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				as.AccountID = value.String
			}
		case achievementssnapshot.FieldReferenceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value.Valid {
				as.ReferenceID = value.String
			}
		case achievementssnapshot.FieldBattles:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field battles", values[i])
			} else if value.Valid {
				as.Battles = int(value.Int64)
			}
		case achievementssnapshot.FieldLastBattleTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_battle_time", values[i])
			} else if value.Valid {
				as.LastBattleTime = value.Int64
			}
		case achievementssnapshot.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &as.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		default:
			as.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AchievementsSnapshot.
// This includes values selected through modifiers, order, etc.
func (as *AchievementsSnapshot) Value(name string) (ent.Value, error) {
	return as.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AchievementsSnapshot entity.
func (as *AchievementsSnapshot) QueryAccount() *AccountQuery {
	return NewAchievementsSnapshotClient(as.config).QueryAccount(as)
}

// Update returns a builder for updating this AchievementsSnapshot.
// Note that you need to call AchievementsSnapshot.Unwrap() before calling this method if this AchievementsSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (as *AchievementsSnapshot) Update() *AchievementsSnapshotUpdateOne {
	return NewAchievementsSnapshotClient(as.config).UpdateOne(as)
}

// Unwrap unwraps the AchievementsSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (as *AchievementsSnapshot) Unwrap() *AchievementsSnapshot {
	_tx, ok := as.config.driver.(*txDriver)
	if !ok {
		panic("db: AchievementsSnapshot is not a transactional entity")
	}
	as.config.driver = _tx.drv
	return as
}

// String implements the fmt.Stringer.
func (as *AchievementsSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("AchievementsSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", as.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", as.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", as.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", as.Type))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(as.AccountID)
	builder.WriteString(", ")
	builder.WriteString("reference_id=")
	builder.WriteString(as.ReferenceID)
	builder.WriteString(", ")
	builder.WriteString("battles=")
	builder.WriteString(fmt.Sprintf("%v", as.Battles))
	builder.WriteString(", ")
	builder.WriteString("last_battle_time=")
	builder.WriteString(fmt.Sprintf("%v", as.LastBattleTime))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", as.Data))
	builder.WriteByte(')')
	return builder.String()
}

// AchievementsSnapshots is a parsable slice of AchievementsSnapshot.
type AchievementsSnapshots []*AchievementsSnapshot
