// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cufee/aftermath/internal/database/ent/db/crontask"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
)

// CronTaskQuery is the builder for querying CronTask entities.
type CronTaskQuery struct {
	config
	ctx        *QueryContext
	order      []crontask.OrderOption
	inters     []Interceptor
	predicates []predicate.CronTask
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CronTaskQuery builder.
func (ctq *CronTaskQuery) Where(ps ...predicate.CronTask) *CronTaskQuery {
	ctq.predicates = append(ctq.predicates, ps...)
	return ctq
}

// Limit the number of records to be returned by this query.
func (ctq *CronTaskQuery) Limit(limit int) *CronTaskQuery {
	ctq.ctx.Limit = &limit
	return ctq
}

// Offset to start from.
func (ctq *CronTaskQuery) Offset(offset int) *CronTaskQuery {
	ctq.ctx.Offset = &offset
	return ctq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctq *CronTaskQuery) Unique(unique bool) *CronTaskQuery {
	ctq.ctx.Unique = &unique
	return ctq
}

// Order specifies how the records should be ordered.
func (ctq *CronTaskQuery) Order(o ...crontask.OrderOption) *CronTaskQuery {
	ctq.order = append(ctq.order, o...)
	return ctq
}

// First returns the first CronTask entity from the query.
// Returns a *NotFoundError when no CronTask was found.
func (ctq *CronTaskQuery) First(ctx context.Context) (*CronTask, error) {
	nodes, err := ctq.Limit(1).All(setContextOp(ctx, ctq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{crontask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctq *CronTaskQuery) FirstX(ctx context.Context) *CronTask {
	node, err := ctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CronTask ID from the query.
// Returns a *NotFoundError when no CronTask ID was found.
func (ctq *CronTaskQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ctq.Limit(1).IDs(setContextOp(ctx, ctq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{crontask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctq *CronTaskQuery) FirstIDX(ctx context.Context) string {
	id, err := ctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CronTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CronTask entity is found.
// Returns a *NotFoundError when no CronTask entities are found.
func (ctq *CronTaskQuery) Only(ctx context.Context) (*CronTask, error) {
	nodes, err := ctq.Limit(2).All(setContextOp(ctx, ctq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{crontask.Label}
	default:
		return nil, &NotSingularError{crontask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctq *CronTaskQuery) OnlyX(ctx context.Context) *CronTask {
	node, err := ctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CronTask ID in the query.
// Returns a *NotSingularError when more than one CronTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctq *CronTaskQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ctq.Limit(2).IDs(setContextOp(ctx, ctq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{crontask.Label}
	default:
		err = &NotSingularError{crontask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctq *CronTaskQuery) OnlyIDX(ctx context.Context) string {
	id, err := ctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CronTasks.
func (ctq *CronTaskQuery) All(ctx context.Context) ([]*CronTask, error) {
	ctx = setContextOp(ctx, ctq.ctx, "All")
	if err := ctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CronTask, *CronTaskQuery]()
	return withInterceptors[[]*CronTask](ctx, ctq, qr, ctq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ctq *CronTaskQuery) AllX(ctx context.Context) []*CronTask {
	nodes, err := ctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CronTask IDs.
func (ctq *CronTaskQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ctq.ctx.Unique == nil && ctq.path != nil {
		ctq.Unique(true)
	}
	ctx = setContextOp(ctx, ctq.ctx, "IDs")
	if err = ctq.Select(crontask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctq *CronTaskQuery) IDsX(ctx context.Context) []string {
	ids, err := ctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctq *CronTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Count")
	if err := ctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ctq, querierCount[*CronTaskQuery](), ctq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ctq *CronTaskQuery) CountX(ctx context.Context) int {
	count, err := ctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctq *CronTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Exist")
	switch _, err := ctq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ctq *CronTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := ctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CronTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctq *CronTaskQuery) Clone() *CronTaskQuery {
	if ctq == nil {
		return nil
	}
	return &CronTaskQuery{
		config:     ctq.config,
		ctx:        ctq.ctx.Clone(),
		order:      append([]crontask.OrderOption{}, ctq.order...),
		inters:     append([]Interceptor{}, ctq.inters...),
		predicates: append([]predicate.CronTask{}, ctq.predicates...),
		// clone intermediate query.
		sql:  ctq.sql.Clone(),
		path: ctq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CronTask.Query().
//		GroupBy(crontask.FieldCreatedAt).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (ctq *CronTaskQuery) GroupBy(field string, fields ...string) *CronTaskGroupBy {
	ctq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CronTaskGroupBy{build: ctq}
	grbuild.flds = &ctq.ctx.Fields
	grbuild.label = crontask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int `json:"created_at,omitempty"`
//	}
//
//	client.CronTask.Query().
//		Select(crontask.FieldCreatedAt).
//		Scan(ctx, &v)
func (ctq *CronTaskQuery) Select(fields ...string) *CronTaskSelect {
	ctq.ctx.Fields = append(ctq.ctx.Fields, fields...)
	sbuild := &CronTaskSelect{CronTaskQuery: ctq}
	sbuild.label = crontask.Label
	sbuild.flds, sbuild.scan = &ctq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CronTaskSelect configured with the given aggregations.
func (ctq *CronTaskQuery) Aggregate(fns ...AggregateFunc) *CronTaskSelect {
	return ctq.Select().Aggregate(fns...)
}

func (ctq *CronTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ctq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ctq); err != nil {
				return err
			}
		}
	}
	for _, f := range ctq.ctx.Fields {
		if !crontask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if ctq.path != nil {
		prev, err := ctq.path(ctx)
		if err != nil {
			return err
		}
		ctq.sql = prev
	}
	return nil
}

func (ctq *CronTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CronTask, error) {
	var (
		nodes = []*CronTask{}
		_spec = ctq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CronTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CronTask{config: ctq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ctq *CronTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctq.querySpec()
	_spec.Node.Columns = ctq.ctx.Fields
	if len(ctq.ctx.Fields) > 0 {
		_spec.Unique = ctq.ctx.Unique != nil && *ctq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ctq.driver, _spec)
}

func (ctq *CronTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(crontask.Table, crontask.Columns, sqlgraph.NewFieldSpec(crontask.FieldID, field.TypeString))
	_spec.From = ctq.sql
	if unique := ctq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ctq.path != nil {
		_spec.Unique = true
	}
	if fields := ctq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, crontask.FieldID)
		for i := range fields {
			if fields[i] != crontask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctq *CronTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctq.driver.Dialect())
	t1 := builder.Table(crontask.Table)
	columns := ctq.ctx.Fields
	if len(columns) == 0 {
		columns = crontask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctq.sql != nil {
		selector = ctq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctq.ctx.Unique != nil && *ctq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ctq.predicates {
		p(selector)
	}
	for _, p := range ctq.order {
		p(selector)
	}
	if offset := ctq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CronTaskGroupBy is the group-by builder for CronTask entities.
type CronTaskGroupBy struct {
	selector
	build *CronTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctgb *CronTaskGroupBy) Aggregate(fns ...AggregateFunc) *CronTaskGroupBy {
	ctgb.fns = append(ctgb.fns, fns...)
	return ctgb
}

// Scan applies the selector query and scans the result into the given value.
func (ctgb *CronTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctgb.build.ctx, "GroupBy")
	if err := ctgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CronTaskQuery, *CronTaskGroupBy](ctx, ctgb.build, ctgb, ctgb.build.inters, v)
}

func (ctgb *CronTaskGroupBy) sqlScan(ctx context.Context, root *CronTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ctgb.fns))
	for _, fn := range ctgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ctgb.flds)+len(ctgb.fns))
		for _, f := range *ctgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ctgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CronTaskSelect is the builder for selecting fields of CronTask entities.
type CronTaskSelect struct {
	*CronTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cts *CronTaskSelect) Aggregate(fns ...AggregateFunc) *CronTaskSelect {
	cts.fns = append(cts.fns, fns...)
	return cts
}

// Scan applies the selector query and scans the result into the given value.
func (cts *CronTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cts.ctx, "Select")
	if err := cts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CronTaskQuery, *CronTaskSelect](ctx, cts.CronTaskQuery, cts, cts.inters, v)
}

func (cts *CronTaskSelect) sqlScan(ctx context.Context, root *CronTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cts.fns))
	for _, fn := range cts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
