// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cufee/aftermath/internal/database/ent/db/discordinteraction"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
	"github.com/cufee/aftermath/internal/database/ent/db/user"
)

// DiscordInteractionQuery is the builder for querying DiscordInteraction entities.
type DiscordInteractionQuery struct {
	config
	ctx        *QueryContext
	order      []discordinteraction.OrderOption
	inters     []Interceptor
	predicates []predicate.DiscordInteraction
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiscordInteractionQuery builder.
func (diq *DiscordInteractionQuery) Where(ps ...predicate.DiscordInteraction) *DiscordInteractionQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit the number of records to be returned by this query.
func (diq *DiscordInteractionQuery) Limit(limit int) *DiscordInteractionQuery {
	diq.ctx.Limit = &limit
	return diq
}

// Offset to start from.
func (diq *DiscordInteractionQuery) Offset(offset int) *DiscordInteractionQuery {
	diq.ctx.Offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DiscordInteractionQuery) Unique(unique bool) *DiscordInteractionQuery {
	diq.ctx.Unique = &unique
	return diq
}

// Order specifies how the records should be ordered.
func (diq *DiscordInteractionQuery) Order(o ...discordinteraction.OrderOption) *DiscordInteractionQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// QueryUser chains the current query on the "user" edge.
func (diq *DiscordInteractionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordinteraction.Table, discordinteraction.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, discordinteraction.UserTable, discordinteraction.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiscordInteraction entity from the query.
// Returns a *NotFoundError when no DiscordInteraction was found.
func (diq *DiscordInteractionQuery) First(ctx context.Context) (*DiscordInteraction, error) {
	nodes, err := diq.Limit(1).All(setContextOp(ctx, diq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{discordinteraction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DiscordInteractionQuery) FirstX(ctx context.Context) *DiscordInteraction {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DiscordInteraction ID from the query.
// Returns a *NotFoundError when no DiscordInteraction ID was found.
func (diq *DiscordInteractionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = diq.Limit(1).IDs(setContextOp(ctx, diq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{discordinteraction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DiscordInteractionQuery) FirstIDX(ctx context.Context) string {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DiscordInteraction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DiscordInteraction entity is found.
// Returns a *NotFoundError when no DiscordInteraction entities are found.
func (diq *DiscordInteractionQuery) Only(ctx context.Context) (*DiscordInteraction, error) {
	nodes, err := diq.Limit(2).All(setContextOp(ctx, diq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{discordinteraction.Label}
	default:
		return nil, &NotSingularError{discordinteraction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DiscordInteractionQuery) OnlyX(ctx context.Context) *DiscordInteraction {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DiscordInteraction ID in the query.
// Returns a *NotSingularError when more than one DiscordInteraction ID is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DiscordInteractionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = diq.Limit(2).IDs(setContextOp(ctx, diq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{discordinteraction.Label}
	default:
		err = &NotSingularError{discordinteraction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DiscordInteractionQuery) OnlyIDX(ctx context.Context) string {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiscordInteractions.
func (diq *DiscordInteractionQuery) All(ctx context.Context) ([]*DiscordInteraction, error) {
	ctx = setContextOp(ctx, diq.ctx, "All")
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DiscordInteraction, *DiscordInteractionQuery]()
	return withInterceptors[[]*DiscordInteraction](ctx, diq, qr, diq.inters)
}

// AllX is like All, but panics if an error occurs.
func (diq *DiscordInteractionQuery) AllX(ctx context.Context) []*DiscordInteraction {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DiscordInteraction IDs.
func (diq *DiscordInteractionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if diq.ctx.Unique == nil && diq.path != nil {
		diq.Unique(true)
	}
	ctx = setContextOp(ctx, diq.ctx, "IDs")
	if err = diq.Select(discordinteraction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DiscordInteractionQuery) IDsX(ctx context.Context) []string {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DiscordInteractionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, diq.ctx, "Count")
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, diq, querierCount[*DiscordInteractionQuery](), diq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DiscordInteractionQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DiscordInteractionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, diq.ctx, "Exist")
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DiscordInteractionQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiscordInteractionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DiscordInteractionQuery) Clone() *DiscordInteractionQuery {
	if diq == nil {
		return nil
	}
	return &DiscordInteractionQuery{
		config:     diq.config,
		ctx:        diq.ctx.Clone(),
		order:      append([]discordinteraction.OrderOption{}, diq.order...),
		inters:     append([]Interceptor{}, diq.inters...),
		predicates: append([]predicate.DiscordInteraction{}, diq.predicates...),
		withUser:   diq.withUser.Clone(),
		// clone intermediate query.
		sql:  diq.sql.Clone(),
		path: diq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DiscordInteractionQuery) WithUser(opts ...func(*UserQuery)) *DiscordInteractionQuery {
	query := (&UserClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withUser = query
	return diq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiscordInteraction.Query().
//		GroupBy(discordinteraction.FieldCreatedAt).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (diq *DiscordInteractionQuery) GroupBy(field string, fields ...string) *DiscordInteractionGroupBy {
	diq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DiscordInteractionGroupBy{build: diq}
	grbuild.flds = &diq.ctx.Fields
	grbuild.label = discordinteraction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DiscordInteraction.Query().
//		Select(discordinteraction.FieldCreatedAt).
//		Scan(ctx, &v)
func (diq *DiscordInteractionQuery) Select(fields ...string) *DiscordInteractionSelect {
	diq.ctx.Fields = append(diq.ctx.Fields, fields...)
	sbuild := &DiscordInteractionSelect{DiscordInteractionQuery: diq}
	sbuild.label = discordinteraction.Label
	sbuild.flds, sbuild.scan = &diq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DiscordInteractionSelect configured with the given aggregations.
func (diq *DiscordInteractionQuery) Aggregate(fns ...AggregateFunc) *DiscordInteractionSelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DiscordInteractionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range diq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, diq); err != nil {
				return err
			}
		}
	}
	for _, f := range diq.ctx.Fields {
		if !discordinteraction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DiscordInteractionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DiscordInteraction, error) {
	var (
		nodes       = []*DiscordInteraction{}
		_spec       = diq.querySpec()
		loadedTypes = [1]bool{
			diq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DiscordInteraction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DiscordInteraction{config: diq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(diq.modifiers) > 0 {
		_spec.Modifiers = diq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := diq.withUser; query != nil {
		if err := diq.loadUser(ctx, query, nodes, nil,
			func(n *DiscordInteraction, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (diq *DiscordInteractionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DiscordInteraction, init func(*DiscordInteraction), assign func(*DiscordInteraction, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DiscordInteraction)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (diq *DiscordInteractionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	if len(diq.modifiers) > 0 {
		_spec.Modifiers = diq.modifiers
	}
	_spec.Node.Columns = diq.ctx.Fields
	if len(diq.ctx.Fields) > 0 {
		_spec.Unique = diq.ctx.Unique != nil && *diq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DiscordInteractionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(discordinteraction.Table, discordinteraction.Columns, sqlgraph.NewFieldSpec(discordinteraction.FieldID, field.TypeString))
	_spec.From = diq.sql
	if unique := diq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if diq.path != nil {
		_spec.Unique = true
	}
	if fields := diq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordinteraction.FieldID)
		for i := range fields {
			if fields[i] != discordinteraction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if diq.withUser != nil {
			_spec.Node.AddColumnOnce(discordinteraction.FieldUserID)
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DiscordInteractionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(discordinteraction.Table)
	columns := diq.ctx.Fields
	if len(columns) == 0 {
		columns = discordinteraction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.ctx.Unique != nil && *diq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range diq.modifiers {
		m(selector)
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (diq *DiscordInteractionQuery) Modify(modifiers ...func(s *sql.Selector)) *DiscordInteractionSelect {
	diq.modifiers = append(diq.modifiers, modifiers...)
	return diq.Select()
}

// DiscordInteractionGroupBy is the group-by builder for DiscordInteraction entities.
type DiscordInteractionGroupBy struct {
	selector
	build *DiscordInteractionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DiscordInteractionGroupBy) Aggregate(fns ...AggregateFunc) *DiscordInteractionGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the selector query and scans the result into the given value.
func (digb *DiscordInteractionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, digb.build.ctx, "GroupBy")
	if err := digb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscordInteractionQuery, *DiscordInteractionGroupBy](ctx, digb.build, digb, digb.build.inters, v)
}

func (digb *DiscordInteractionGroupBy) sqlScan(ctx context.Context, root *DiscordInteractionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*digb.flds)+len(digb.fns))
		for _, f := range *digb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*digb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DiscordInteractionSelect is the builder for selecting fields of DiscordInteraction entities.
type DiscordInteractionSelect struct {
	*DiscordInteractionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DiscordInteractionSelect) Aggregate(fns ...AggregateFunc) *DiscordInteractionSelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DiscordInteractionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dis.ctx, "Select")
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscordInteractionQuery, *DiscordInteractionSelect](ctx, dis.DiscordInteractionQuery, dis, dis.inters, v)
}

func (dis *DiscordInteractionSelect) sqlScan(ctx context.Context, root *DiscordInteractionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dis *DiscordInteractionSelect) Modify(modifiers ...func(s *sql.Selector)) *DiscordInteractionSelect {
	dis.modifiers = append(dis.modifiers, modifiers...)
	return dis
}
