// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cufee/aftermath/internal/database/ent/db/discordinteraction"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
)

// DiscordInteractionDelete is the builder for deleting a DiscordInteraction entity.
type DiscordInteractionDelete struct {
	config
	hooks    []Hook
	mutation *DiscordInteractionMutation
}

// Where appends a list predicates to the DiscordInteractionDelete builder.
func (did *DiscordInteractionDelete) Where(ps ...predicate.DiscordInteraction) *DiscordInteractionDelete {
	did.mutation.Where(ps...)
	return did
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (did *DiscordInteractionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, did.sqlExec, did.mutation, did.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (did *DiscordInteractionDelete) ExecX(ctx context.Context) int {
	n, err := did.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (did *DiscordInteractionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discordinteraction.Table, sqlgraph.NewFieldSpec(discordinteraction.FieldID, field.TypeString))
	if ps := did.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, did.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	did.mutation.done = true
	return affected, err
}

// DiscordInteractionDeleteOne is the builder for deleting a single DiscordInteraction entity.
type DiscordInteractionDeleteOne struct {
	did *DiscordInteractionDelete
}

// Where appends a list predicates to the DiscordInteractionDelete builder.
func (dido *DiscordInteractionDeleteOne) Where(ps ...predicate.DiscordInteraction) *DiscordInteractionDeleteOne {
	dido.did.mutation.Where(ps...)
	return dido
}

// Exec executes the deletion query.
func (dido *DiscordInteractionDeleteOne) Exec(ctx context.Context) error {
	n, err := dido.did.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordinteraction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dido *DiscordInteractionDeleteOne) ExecX(ctx context.Context) {
	if err := dido.Exec(ctx); err != nil {
		panic(err)
	}
}
