// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cufee/aftermath/internal/database/ent/db/leaderboardscore"
	"github.com/cufee/aftermath/internal/database/ent/db/predicate"
)

// LeaderboardScoreDelete is the builder for deleting a LeaderboardScore entity.
type LeaderboardScoreDelete struct {
	config
	hooks    []Hook
	mutation *LeaderboardScoreMutation
}

// Where appends a list predicates to the LeaderboardScoreDelete builder.
func (lsd *LeaderboardScoreDelete) Where(ps ...predicate.LeaderboardScore) *LeaderboardScoreDelete {
	lsd.mutation.Where(ps...)
	return lsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lsd *LeaderboardScoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lsd.sqlExec, lsd.mutation, lsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lsd *LeaderboardScoreDelete) ExecX(ctx context.Context) int {
	n, err := lsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lsd *LeaderboardScoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(leaderboardscore.Table, sqlgraph.NewFieldSpec(leaderboardscore.FieldID, field.TypeString))
	if ps := lsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lsd.mutation.done = true
	return affected, err
}

// LeaderboardScoreDeleteOne is the builder for deleting a single LeaderboardScore entity.
type LeaderboardScoreDeleteOne struct {
	lsd *LeaderboardScoreDelete
}

// Where appends a list predicates to the LeaderboardScoreDelete builder.
func (lsdo *LeaderboardScoreDeleteOne) Where(ps ...predicate.LeaderboardScore) *LeaderboardScoreDeleteOne {
	lsdo.lsd.mutation.Where(ps...)
	return lsdo
}

// Exec executes the deletion query.
func (lsdo *LeaderboardScoreDeleteOne) Exec(ctx context.Context) error {
	n, err := lsdo.lsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{leaderboardscore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lsdo *LeaderboardScoreDeleteOne) ExecX(ctx context.Context) {
	if err := lsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
