name: Fly Deploy to Canary

on:
  push:
    branches:
      - canary
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy app to canary
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - run: flyctl deploy --remote-only -c fly.canary.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_CANARY }}
