name: Deploy with Dokploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create and publish Docker images"]
    types:
      - completed

jobs:
  build-and-push-image:
    environment: dokploy-${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy the application using the latest image
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.DOKPLOY_WEBHOOK_URL }}